---
- name: add repostitory keys
  apt_key:
    keyserver=hkp://keyserver.ubuntu.com:80
    id=EA312927
    state=present
- name: Add the source.list
  lineinfile: >
    line="deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"
    dest=/etc/apt/sources.list.d/mongodb-org-3.2.list
    state=present
    create=yes
- name: creating a mongodb configuration file
  file: path=/etc/systemd/system/mongodb.service state=touch 
- name: Update the conf fiel
  lineinfile:
    dest=/etc/systemd/system/mongodb.service
    line="----------------------------
              [Unit]
            Description=High-performance, schema-free document-oriented database
            After=network.target

              [Service]
            User=mongodb
            ExecStart=/usr/bin/mongod --quiet --config /etc/mongod.conf

              [Install]
            WantedBy=multi-user.target
          ----------------------------------"
    
- name: Install mongo
  apt: name=mongodb-org state=present update_cache=yes
  notify: start mongodb