---
- name: add repostitory keys
  apt_key:
    keyserver=hkp://keyserver.ubuntu.com:80
    id=EA312927
    state=present
- name: Add the source.list
  lineinfile: >
    line="deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"
    dest=/etc/apt/sources.list.d/mongodb-org-3.2.list
    state=present
    create=yes
- name: copying configurations
  become: yes
  copy:
    src: /home/yash/scripts/ansibles-final/roles/mongodb/files/mongodb.service
    dest: /etc/systemd/system/mongodb.service


    
- name: Install mongo
  apt: name=mongodb-org state=present update_cache=yes
  notify: start mongodb


