---
- name: install software for Hygieia
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - git
    - maven

- name: Final Check for version
  command: mvn -version
  register: check
- debug: msg="{{ check.stdout }}"