---
- name: install python 
  apt: name=python3-pip state=present update_cache=yes
- name: install other dependies
  apt: name={{item}}  state=present 
  with_items:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python3-dev